---
title: "Lectura de los datos"
author: "Miguel Ángel Londoño Ciceros"
date: "19/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lectura de los datos


```{r}
df <- read.csv("base_trabajo_segmentacion.csv", sep = ";", dec = '.', header = T)

head(df)
```

```{r}
which(duplicated(df$nit))
```

```{r}
a <- df[which(duplicated(df$nit)), ]

unique(a$nit)
```


```{r}
df[(which(df$pagos_pj + df$pagos_pn == 0)), ]
```



```{r}
df <- df[, -1]
```

```{r}
str(df)
```
```{r}
summary(df)
```

```{r}
plot(df[, 1:5])
```


```{r}
for (i in 1:46){
  boxplot(df[, i], main = paste("Hist de ", names(df)[i]))
}

```

```{r}
df_scaled <- scale(df, center = T, scale = T)
```


# Reducción de la dimensionalidad

```{r}
library("FactoMineR")
```

## PCA

```{r}
comp_prin <- PCA(df_scaled, ncp = 3, scale.unit = T)
```
```{r}
(pca_df <- comp_prin$eig)
```

```{r}
plot(1:46, pca_df[, 3])
```


```{r}
comp_prin$var
```


```{r}
require(factoextra)

fviz_screeplot(comp_prin, addlabels = TRUE, ylim = c(0, 20))
```
```{r}
fviz_contrib(comp_prin, choice = "var", axes = 1, top = 10)
```
```{r}
fviz_contrib(comp_prin, choice = "var", axes = 2, top = 10)
```


```{r}
require(plot3D)


plot3D::points3D(comp_prin$ind$coord[, 1], 
                 comp_prin$ind$coord[, 2], 
                 comp_prin$ind$coord[, 3])

require(plotly)

a <- as.data.frame(comp_prin$ind$coord)

plot_ly(data = a,
        x=~Dim.1, 
        y=~Dim.2,
        z=~Dim.3)

```




```{r}
res.hcpc <- HCPC(comp_prin, graph = FALSE)



fviz_dend(res.hcpc, 
          cex = 0.7,                     # Label size
          palette = "jco",               # Color palette see ?ggpubr::ggpar
          rect = TRUE, rect_fill = TRUE, # Add rectangle around groups
          rect_border = "jco",           # Rectangle color
          labels_track_height = 0.8      # Augment the room for labels
)
```










```{r}
fviz_cluster(res.hcpc,
             repel = TRUE,            # Avoid label overlapping
             show.clust.cent = TRUE, # Show cluster centers
             palette = "jco",         # Color palette see ?ggpubr::ggpar
             ggtheme = theme_minimal(),
             main = "Factor map"
             )
```

# MFA


```{r}
datos_mfa <-as.data.frame(df_scaled)


datos_mfa[, 31:35] <- apply(df[, 31:35], 2, as.factor) 

datos_mfa[, 38:39] <- apply(df[, 38:39], 2, as.factor) 

datos_mfa[, 42:46] <- apply(df[, 42:46], 2, as.factor)

```



```{r}
str(datos_mfa)
```


```{r}
res.mfa <- MFA(datos_mfa, 
               group = c(11, 11, 4, 4, 5, 2, 2, 2, 5),
               type = c('s', 's', 's', 's', 'n', 's', 'n', 's', 'n'),
               name.group = c('en_vm', 'en_tx', 'sal_vm', 'sal_tx', 'cat1', 'pagos', 'ventas', 'recaudos', 'rotacion_ciclo'), graph = T)
```

```{r}
res.mfa$eig
```




# Intentando escalar de otra forma

## Eliminando los outliers


```{r}
matrix_dist <- dist(df_scaled, upper = TRUE)

distancias <- as.matrix(matrix_dist)[1, ]

dim(distancias)
```

```{r}
outliers <- as.numeric(names(sort(distancias, decreasing = T)[1:400]))
```

```{r}
outliers[1:10]
```

```{r}
row.names(datos_arbol[datos_arbol[, 'Y'] == 3, ])


cat_3_outliers <- c(825, 1416, 1462, 1668, 1773)
```

```{r}

robust_scaler <- function(columna){
  
  # value = (value – median) / (p75 – p25)
  
  denominador <- IQR(columna) + 0.000000001
  
  col_scaled <- columna - median(columna)
  
  col_scaled <- col_scaled/denominador
  
  return(col_scaled)
}


df_robscale <- apply(df, 2, robust_scaler)

```


```{r}
FactoMineR::PCA(df_robscale[-outliers, ], ncp = 3, graph = T)
```

# Kmeans 

```{r}

require(cluster)

kc <- kmeans(df_robscale[-outliers, ], 3 , nstart = 5, iter.max = 100)

clusplot(df_robscale[-outliers, ], kc$cluster, color = TRUE, 
          shade = FALSE, labels = 4, lines = 1,
          col.p = kc$cluster )
```




# K means

```{r}
# Clustering iterativo kmeans
x <- NULL
for ( i in 1:10 ){
  kc     <- kmeans(df, i)
  x[ i ] <- kc$tot.withinss
}
plot( c( 1:10 ), x, type = "b" )
```

```{r}
# Clustering iterativo kmeans
x <- NULL
for ( i in 1:10 ){
  kc     <- kmeans(df_robscale, i)
  x[ i ] <- kc$tot.withinss
}
plot( c( 1:10 ), x, type = "b" )
```


```{r}
require(ggplot2)

set.seed(1234)
wcss <- vector()
for(i in 1:20){
  wcss[i] <- sum(kmeans(df_robscale, i)$withinss)
}
ggplot() + geom_point(aes(x = 1:20, y = wcss), color = 'blue') + 
  geom_line(aes(x = 1:20, y = wcss), color = 'blue') + 
  ggtitle("Método del Codo") + 
  xlab('Cantidad de Centroides k') + 
  ylab('WCSS')
```

---

```{r}
library(ggdendro)
require(factoextra)

dendrogram <- hclust(dist(df_scaled[-cat_3_outliers, ], method = 'euclidean'), method = 'ward.D')


plot(dendrogram, xlab="", sub="", cex=0.9)
rect.hclust(dendrogram, k=3, border="cyan4")
```
```{r}
ggdendrogram(dendrogram, rotate = FALSE, labels = FALSE, theme_dendro = TRUE)
```


```{r}
km_scaled <- kmeans(df_scaled[-cat_3_outliers, ], 3, nstart = 25, iter.max = 1000)

# km_scaled$cluster

require(cluster)

clusplot(df_scaled[-cat_3_outliers, ], km_scaled$cluster, color = TRUE, 
          shade = FALSE, labels = 4, lines = 1,
          col.p = km_scaled$cluster )

```

```{r}
datos_arbol <- df[-cat_3_outliers, ]

Y <- km_scaled$cluster

Y <- as.factor(Y)

datos_arbol <- data.frame(Y, datos_arbol)
```

```{r}
head(datos_arbol)
```
```{r}
require(tree)

arbol <- tree::tree(Y~., data = datos_arbol)


summary(arbol)
```

```{r}
require(rpart)
require(rpart.plot)

arbol_1 <- rpart(formula = Y~., data = datos_arbol)


rpart.plot(arbol_1)
```
```{r}
y_pred <- predict(arbol_1, newdata = datos_arbol[, -1], type = "class")

table(datos_arbol$Y, y_pred)
```
```{r}
sum(diag(table(datos_arbol$Y, y_pred)))/sum(table(datos_arbol$Y, y_pred))
```

